### ISSUE TITLE
Reloadskin health again

### ISSUE THREAD

**Issue by Topnetworks** [ihyajb/aj-fivem-appearance#16]
So i took half damage (half health left) then i reload skin witch puts me back to same health but then its like your in god mode and can not take anymore damage..

also did /kill witch kills me but when i do /revive it puts me back at the % of health i was at when i did the reloadskin.

Cheers,
Les

**Comment by Dextroamphetamine** [comment]
I fixed this issue with 

`RegisterCommand("reloadskin", function()

    local playerPed = PlayerPedId()
    local maxhealth = GetEntityMaxHealth(playerPed)
    local health = GetEntityHealth(playerPed)

	PlayerData = QBCore.Functions.GetPlayerData()
	local skin = 'mp_m_freemode_01'
	if PlayerData.charinfo.gender == 1 then
		skin = "mp_f_freemode_01"
	end
	local config = {
		ped = true,
		headBlend = true,
		faceFeatures = true,
		headOverlays = true,
		components = true,
		props = true,
	}
	QBCore.Functions.TriggerCallback('fivem-appearance:getPlayerSkin', function(appearance) --- trigger callback on setPlayerAppearance if not work
	exports['fivem-appearance']:setPlayerAppearance(appearance, config)
    SetPedMaxHealth(PlayerId(), maxhealth)
    Citizen.Wait(1000) -- Safety Delay
    SetEntityHealth(PlayerPedId(), health)
	end, true)
end)`

**Comment by Topnetworks** [comment]
> I fixed this issue with
> 
> ` RegisterCommand("reloadskin", function()
> 
> ```
> local playerPed = PlayerPedId()
> local maxhealth = GetEntityMaxHealth(playerPed)
> local health = GetEntityHealth(playerPed)
> 
> PlayerData = QBCore.Functions.GetPlayerData()
> local skin = 'mp_m_freemode_01'
> if PlayerData.charinfo.gender == 1 then
> 	skin = "mp_f_freemode_01"
> end
> local config = {
> 	ped = true,
> 	headBlend = true,
> 	faceFeatures = true,
> 	headOverlays = true,
> 	components = true,
> 	props = true,
> }
> QBCore.Functions.TriggerCallback('fivem-appearance:getPlayerSkin', function(appearance)
> exports['fivem-appearance']:setPlayerAppearance(appearance, config)
> SetPedMaxHealth(PlayerId(), maxhealth)
> Citizen.Wait(1000) -- Safety Delay
> SetEntityHealth(PlayerPedId(), health)
> end, true)
> ```
> 
> end) `

Nice one bro... good  work.
