### ISSUE TITLE
[BUG] Buy clothes without any deductions

### ISSUE THREAD

**Issue by MercedessBenz** [ihyajb/aj-fivem-appearance#6]
I have set a purchase price for clothes is 500$

But the money is not deducted, and even if I don't have money, I can still buy clothes

**Comment by zeemkarry** [comment]
> I have set a purchase price for clothes is 500$
> 
> But the money is not deducted, and even if I don't have money, I can still buy clothes

use config to set price

**Comment by Riggsee** [comment]
LN 58 server.lua change the < to a > after Config.Money
